# Generated by Django 5.1.6 on 2025-03-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_participantnotification_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voted_project', to='home.attendee'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('participant', 'project')},
        ),
    ]
