# Generated by Django 5.1.6 on 2025-03-01 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sociallinks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='votecount',
            name='id',
        ),
        migrations.AlterField(
            model_name='likecount',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='like_count', serialize=False, to='home.project'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='social_links', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votecount',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vote_count', serialize=False, to='home.project'),
        ),
    ]
