# Generated by Django 5.1.6 on 2025-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_participant_about_alter_vote_attendee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='designation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='domain',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='commudle_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
