# Generated by Django 5.1.6 on 2025-03-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_participant_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_registered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
