name: Backup SQLite to Google Drive

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Create Credentials File
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > credentials.json

      - name: Upload SQLite to Google Drive
        run: python backup.py
