name: Backup SQLite to Google Drive

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write  # 👈 This gives GitHub Actions permission to push changes

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

      - name: Create credentials.json
        run: echo '${{ secrets.GDRIVE_CREDENTIALS }}' > credentials.json

      - name: Run backup script
        run: python backup.py

      - name: Push changes to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -f db.sqlite3  # Force tracking of db.sqlite3
          git commit -m "Updated db.sqlite3 - $(date)" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
