name: Backup SQLite to Google Drive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 googleapiclient requests

      - name: Create credentials.json
        run: echo '${{ secrets.GDRIVE_CREDENTIALS }}' > credentials.json

      - name: Run backup script
        run: python backup.py
